/*
 * Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.
 *
 * Licensed under the MIT (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://github.com/aspose-omr-cloud/aspose-omr-cloud-java/blob/master/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Aspose.OMR for Cloud API Reference
 * Aspose.OMR for Cloud helps performing optical mark recognition in the cloud
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.omr.model;

import java.util.Objects;
import com.aspose.omr.model.OMRResponseDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents information about OMR result.
 */
@ApiModel(description = "Represents information about OMR result.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-18T16:51:05.078+03:00")
public class OmrResponseInfo {
  @SerializedName("ResponseVersion")
  private String responseVersion = null;

  @SerializedName("ProcessedTasksCount")
  private Integer processedTasksCount = null;

  @SerializedName("SuccessfulTasksCount")
  private Integer successfulTasksCount = null;

  @SerializedName("Details")
  private OMRResponseDetails details = null;

  public OmrResponseInfo responseVersion(String responseVersion) {
    this.responseVersion = responseVersion;
    return this;
  }

   /**
   * String value representing version of the response.
   * @return responseVersion
  **/
  @ApiModelProperty(value = "String value representing version of the response.")
  public String getResponseVersion() {
    return responseVersion;
  }

  public void setResponseVersion(String responseVersion) {
    this.responseVersion = responseVersion;
  }

  public OmrResponseInfo processedTasksCount(Integer processedTasksCount) {
    this.processedTasksCount = processedTasksCount;
    return this;
  }

   /**
   * Total amount of processed tasks
   * @return processedTasksCount
  **/
  @ApiModelProperty(required = true, value = "Total amount of processed tasks")
  public Integer getProcessedTasksCount() {
    return processedTasksCount;
  }

  public void setProcessedTasksCount(Integer processedTasksCount) {
    this.processedTasksCount = processedTasksCount;
  }

  public OmrResponseInfo successfulTasksCount(Integer successfulTasksCount) {
    this.successfulTasksCount = successfulTasksCount;
    return this;
  }

   /**
   * Total amount of successful tasks, i.e. tasks that completed without errors
   * @return successfulTasksCount
  **/
  @ApiModelProperty(required = true, value = "Total amount of successful tasks, i.e. tasks that completed without errors")
  public Integer getSuccessfulTasksCount() {
    return successfulTasksCount;
  }

  public void setSuccessfulTasksCount(Integer successfulTasksCount) {
    this.successfulTasksCount = successfulTasksCount;
  }

  public OmrResponseInfo details(OMRResponseDetails details) {
    this.details = details;
    return this;
  }

   /**
   * Additional information regarding performed task.
   * @return details
  **/
  @ApiModelProperty(value = "Additional information regarding performed task.")
  public OMRResponseDetails getDetails() {
    return details;
  }

  public void setDetails(OMRResponseDetails details) {
    this.details = details;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OmrResponseInfo omrResponseInfo = (OmrResponseInfo) o;
    return Objects.equals(this.responseVersion, omrResponseInfo.responseVersion) &&
        Objects.equals(this.processedTasksCount, omrResponseInfo.processedTasksCount) &&
        Objects.equals(this.successfulTasksCount, omrResponseInfo.successfulTasksCount) &&
        Objects.equals(this.details, omrResponseInfo.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseVersion, processedTasksCount, successfulTasksCount, details);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OmrResponseInfo {\n");
    
    sb.append("    responseVersion: ").append(toIndentedString(responseVersion)).append("\n");
    sb.append("    processedTasksCount: ").append(toIndentedString(processedTasksCount)).append("\n");
    sb.append("    successfulTasksCount: ").append(toIndentedString(successfulTasksCount)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

