/*
 * Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.
 *
 * Licensed under the MIT (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://github.com/aspose-omr-cloud/aspose-omr-cloud-java/blob/master/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Aspose.OMR for Cloud API Reference
 * Aspose.OMR for Cloud helps performing optical mark recognition in the cloud
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.omr.model;

import java.util.Objects;
import com.aspose.omr.model.RecognitionStatistics;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Structure that holds additional information regarding performed task.
 */
@ApiModel(description = "Structure that holds additional information regarding performed task.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-18T16:51:05.078+03:00")
public class OMRResponseDetails {
  @SerializedName("TaskMessages")
  private java.util.List<String> taskMessages = null;

  @SerializedName("TaskResult")
  private String taskResult = null;

  @SerializedName("RecognitionStatistics")
  private java.util.List<RecognitionStatistics> recognitionStatistics = null;

  public OMRResponseDetails taskMessages(java.util.List<String> taskMessages) {
    this.taskMessages = taskMessages;
    return this;
  }

  public OMRResponseDetails addTaskMessagesItem(String taskMessagesItem) {
    if (this.taskMessages == null) {
      this.taskMessages = new java.util.ArrayList<String>();
    }
    this.taskMessages.add(taskMessagesItem);
    return this;
  }

   /**
   * Warnings and other messages regarding task, etc.
   * @return taskMessages
  **/
  @ApiModelProperty(value = "Warnings and other messages regarding task, etc.")
  public java.util.List<String> getTaskMessages() {
    return taskMessages;
  }

  public void setTaskMessages(java.util.List<String> taskMessages) {
    this.taskMessages = taskMessages;
  }

  public OMRResponseDetails taskResult(String taskResult) {
    this.taskResult = taskResult;
    return this;
  }

   /**
   * Indicates if each particular task passed or failed,
   * @return taskResult
  **/
  @ApiModelProperty(value = "Indicates if each particular task passed or failed,")
  public String getTaskResult() {
    return taskResult;
  }

  public void setTaskResult(String taskResult) {
    this.taskResult = taskResult;
  }

  public OMRResponseDetails recognitionStatistics(java.util.List<RecognitionStatistics> recognitionStatistics) {
    this.recognitionStatistics = recognitionStatistics;
    return this;
  }

  public OMRResponseDetails addRecognitionStatisticsItem(RecognitionStatistics recognitionStatisticsItem) {
    if (this.recognitionStatistics == null) {
      this.recognitionStatistics = new java.util.ArrayList<RecognitionStatistics>();
    }
    this.recognitionStatistics.add(recognitionStatisticsItem);
    return this;
  }

   /**
   * RecognitionStatistics
   * @return recognitionStatistics
  **/
  @ApiModelProperty(value = "RecognitionStatistics")
  public java.util.List<RecognitionStatistics> getRecognitionStatistics() {
    return recognitionStatistics;
  }

  public void setRecognitionStatistics(java.util.List<RecognitionStatistics> recognitionStatistics) {
    this.recognitionStatistics = recognitionStatistics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OMRResponseDetails omRResponseDetails = (OMRResponseDetails) o;
    return Objects.equals(this.taskMessages, omRResponseDetails.taskMessages) &&
        Objects.equals(this.taskResult, omRResponseDetails.taskResult) &&
        Objects.equals(this.recognitionStatistics, omRResponseDetails.recognitionStatistics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskMessages, taskResult, recognitionStatistics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OMRResponseDetails {\n");
    
    sb.append("    taskMessages: ").append(toIndentedString(taskMessages)).append("\n");
    sb.append("    taskResult: ").append(toIndentedString(taskResult)).append("\n");
    sb.append("    recognitionStatistics: ").append(toIndentedString(recognitionStatistics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

