/*
 * Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.
 *
 * Licensed under the MIT (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://github.com/aspose-omr-cloud/aspose-omr-cloud-java/blob/master/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Aspose.OMR for Cloud API Reference
 * Aspose.OMR for Cloud helps performing optical mark recognition in the cloud
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.omr.model;

import java.util.Objects;
import com.aspose.omr.model.AsposeResponse;
import com.aspose.omr.model.Payload;
import com.aspose.omr.model.ServerStat;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents information about response after OMR.
 */
@ApiModel(description = "Represents information about response after OMR.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-18T16:51:05.078+03:00")
public class OMRResponse {
  @SerializedName("Status")
  private String status = null;

  @SerializedName("ErrorCode")
  private Integer errorCode = null;

  @SerializedName("ErrorText")
  private String errorText = null;

  @SerializedName("Payload")
  private Payload payload = null;

  @SerializedName("ServerStat")
  private ServerStat serverStat = null;

  public OMRResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Indicates operation&#39;s status
   * @return status
  **/
  @ApiModelProperty(value = "Indicates operation's status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public OMRResponse errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Integer field that indicates whether any critical errors occured during task execution
   * @return errorCode
  **/
  @ApiModelProperty(value = "Integer field that indicates whether any critical errors occured during task execution")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public OMRResponse errorText(String errorText) {
    this.errorText = errorText;
    return this;
  }

   /**
   * String description of occured critical error. Empty if no critical errors occured
   * @return errorText
  **/
  @ApiModelProperty(value = "String description of occured critical error. Empty if no critical errors occured")
  public String getErrorText() {
    return errorText;
  }

  public void setErrorText(String errorText) {
    this.errorText = errorText;
  }

  public OMRResponse payload(Payload payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Payload
   * @return payload
  **/
  @ApiModelProperty(value = "Payload")
  public Payload getPayload() {
    return payload;
  }

  public void setPayload(Payload payload) {
    this.payload = payload;
  }

  public OMRResponse serverStat(ServerStat serverStat) {
    this.serverStat = serverStat;
    return this;
  }

   /**
   * Server statistics
   * @return serverStat
  **/
  @ApiModelProperty(value = "Server statistics")
  public ServerStat getServerStat() {
    return serverStat;
  }

  public void setServerStat(ServerStat serverStat) {
    this.serverStat = serverStat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OMRResponse omRResponse = (OMRResponse) o;
    return Objects.equals(this.status, omRResponse.status) &&
        Objects.equals(this.errorCode, omRResponse.errorCode) &&
        Objects.equals(this.errorText, omRResponse.errorText) &&
        Objects.equals(this.payload, omRResponse.payload) &&
        Objects.equals(this.serverStat, omRResponse.serverStat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, errorCode, errorText, payload, serverStat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OMRResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorText: ").append(toIndentedString(errorText)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    serverStat: ").append(toIndentedString(serverStat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

