/*
 * Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.
 *
 * Licensed under the MIT (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://github.com/aspose-omr-cloud/aspose-omr-cloud-java/blob/master/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Aspose.OMR for Cloud API Reference
 * Aspose.OMR for Cloud helps performing optical mark recognition in the cloud
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.omr.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OMRResponseDetails
 */
@ApiModel(description = "OMRResponseDetails")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-18T16:51:05.078+03:00")
public class RecognitionStatistics {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("TaskMessages")
  private java.util.List<String> taskMessages = null;

  @SerializedName("TaskResult")
  private String taskResult = null;

  @SerializedName("RunSeconds")
  private Double runSeconds = null;

  public RecognitionStatistics name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Gets or sets Name
   * @return name
  **/
  @ApiModelProperty(value = "Gets or sets Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RecognitionStatistics taskMessages(java.util.List<String> taskMessages) {
    this.taskMessages = taskMessages;
    return this;
  }

  public RecognitionStatistics addTaskMessagesItem(String taskMessagesItem) {
    if (this.taskMessages == null) {
      this.taskMessages = new java.util.ArrayList<String>();
    }
    this.taskMessages.add(taskMessagesItem);
    return this;
  }

   /**
   * Warnings and other messages regarding task, etc.
   * @return taskMessages
  **/
  @ApiModelProperty(value = "Warnings and other messages regarding task, etc.")
  public java.util.List<String> getTaskMessages() {
    return taskMessages;
  }

  public void setTaskMessages(java.util.List<String> taskMessages) {
    this.taskMessages = taskMessages;
  }

  public RecognitionStatistics taskResult(String taskResult) {
    this.taskResult = taskResult;
    return this;
  }

   /**
   * Indicates if each particular task passed or failed,
   * @return taskResult
  **/
  @ApiModelProperty(value = "Indicates if each particular task passed or failed,")
  public String getTaskResult() {
    return taskResult;
  }

  public void setTaskResult(String taskResult) {
    this.taskResult = taskResult;
  }

  public RecognitionStatistics runSeconds(Double runSeconds) {
    this.runSeconds = runSeconds;
    return this;
  }

   /**
   * Gets or sets RunSeconds
   * @return runSeconds
  **/
  @ApiModelProperty(required = true, value = "Gets or sets RunSeconds")
  public Double getRunSeconds() {
    return runSeconds;
  }

  public void setRunSeconds(Double runSeconds) {
    this.runSeconds = runSeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecognitionStatistics recognitionStatistics = (RecognitionStatistics) o;
    return Objects.equals(this.name, recognitionStatistics.name) &&
        Objects.equals(this.taskMessages, recognitionStatistics.taskMessages) &&
        Objects.equals(this.taskResult, recognitionStatistics.taskResult) &&
        Objects.equals(this.runSeconds, recognitionStatistics.runSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, taskMessages, taskResult, runSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecognitionStatistics {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    taskMessages: ").append(toIndentedString(taskMessages)).append("\n");
    sb.append("    taskResult: ").append(toIndentedString(taskResult)).append("\n");
    sb.append("    runSeconds: ").append(toIndentedString(runSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

