/*
 * Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.
 *
 * Licensed under the MIT (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://github.com/aspose-omr-cloud/aspose-omr-cloud-java/blob/master/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Aspose.OMR for Cloud API Reference
 * Aspose.OMR for Cloud helps performing optical mark recognition in the cloud
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.omr.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents information about part of the text.
 */
@ApiModel(description = "Represents information about part of the text.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-18T16:51:05.078+03:00")
public class ServerStat {
  @SerializedName("StorageDownloadTime")
  private String storageDownloadTime = null;

  @SerializedName("OmrFunctionCallTime")
  private String omrFunctionCallTime = null;

  public ServerStat storageDownloadTime(String storageDownloadTime) {
    this.storageDownloadTime = storageDownloadTime;
    return this;
  }

   /**
   * Get or set StorageDownloadTime
   * @return storageDownloadTime
  **/
  @ApiModelProperty(required = true, value = "Get or set StorageDownloadTime")
  public String getStorageDownloadTime() {
    return storageDownloadTime;
  }

  public void setStorageDownloadTime(String storageDownloadTime) {
    this.storageDownloadTime = storageDownloadTime;
  }

  public ServerStat omrFunctionCallTime(String omrFunctionCallTime) {
    this.omrFunctionCallTime = omrFunctionCallTime;
    return this;
  }

   /**
   * Get or set OmrFunctionCallTime
   * @return omrFunctionCallTime
  **/
  @ApiModelProperty(required = true, value = "Get or set OmrFunctionCallTime")
  public String getOmrFunctionCallTime() {
    return omrFunctionCallTime;
  }

  public void setOmrFunctionCallTime(String omrFunctionCallTime) {
    this.omrFunctionCallTime = omrFunctionCallTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerStat serverStat = (ServerStat) o;
    return Objects.equals(this.storageDownloadTime, serverStat.storageDownloadTime) &&
        Objects.equals(this.omrFunctionCallTime, serverStat.omrFunctionCallTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storageDownloadTime, omrFunctionCallTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerStat {\n");
    
    sb.append("    storageDownloadTime: ").append(toIndentedString(storageDownloadTime)).append("\n");
    sb.append("    omrFunctionCallTime: ").append(toIndentedString(omrFunctionCallTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

